import yaml
import zipfile
import io
import re
import json
from typing import List, Dict, Any
from .schemas import GraphData

import unicodedata

class BlockStr(str):
    """Marcador para strings que devem ser renderizadas como bloco (>) no YAML"""

def block_str_representer(dumper, data):
    return dumper.represent_scalar(u'tag:yaml.org,2002:str', data, style='>')

# Registra o representer globalmente para o SafeDumper
yaml.SafeDumper.add_representer(BlockStr, block_str_representer)

def normalize_text(text: str) -> str:
    """Remove acentos e caracteres especiais para nomes de arquivos/chaves"""
    if not text: return ""
    return "".join(c for c in unicodedata.normalize('NFD', text) if unicodedata.category(c) != 'Mn')

def to_snake_case(text: str) -> str:
    if not text:
        return ""
    # Remove acentos
    text = normalize_text(text)
    # Converte CamelCase para snake_case
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', text)
    s2 = re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()
    # Troca espaços e hífens por underscore
    s3 = s2.replace(" ", "_").replace("-", "_")
    # Remove caracteres não alfanuméricos exceto underscore
    s4 = re.sub(r'[^a-z0-9_]', '', s3)
    # Remove múltiplos underscores seguidos
    return re.sub(r'_+', '_', s4).strip('_')

def clean_text(text: str) -> str:
    """Normaliza o texto para uma única linha (sem quebras) para que o YAML realize a dobra (folding) de forma limpa"""
    if not text: return ""
    # Remove qualquer sequência de espaços ou quebras de linha e substitui por um único espaço
    return " ".join(text.split()).strip()

def extract_placeholders(text: str) -> List[str]:
    """Extrai nomes de variáveis entre chaves {variavel}"""
    if not text:
        return []
    return re.findall(r'\{([a-zA-Z0-9_]+)\}', text)

def generate_python_project(graph_data: GraphData, project_name: str, author_name: str = "SimpleCrew", author_email: str = "admin@simplecrew.ai", mcp_servers: List[Dict[str, Any]] = None, project_description: str = "", agent_llms: Dict[str, Dict[str, Any]] = None, providers: List[str] = None, workspace_path: str = None) -> bytes:
    """
    Transforma GraphData em um arquivo ZIP contendo um projeto CrewAI completo.
    """
    # Sanitização básica do nome do projeto para pastas
    folder_name = to_snake_case(project_name)
    if not folder_name:
        folder_name = "my_crew_project"

    buffer = io.BytesIO()
    
    with zipfile.ZipFile(buffer, 'a', zipfile.ZIP_DEFLATED, False) as zip_file:
        # 1. .env
        env_lines = []
        needed_keys = []
        providers = providers or ["openai"]
        if "openai" in providers:
            env_lines.append("OPENAI_API_KEY=your_openai_api_key_here")
            needed_keys.append("OPENAI_API_KEY")
        if "anthropic" in providers:
            env_lines.append("ANTHROPIC_API_KEY=your_anthropic_api_key_here")
            needed_keys.append("ANTHROPIC_API_KEY")
        if "google" in providers:
            env_lines.append("GOOGLE_API_KEY=your_google_api_key_here")
            needed_keys.append("GOOGLE_API_KEY")
        if "groq" in providers:
            env_lines.append("GROQ_API_KEY=your_groq_api_key_here")
            needed_keys.append("GROQ_API_KEY")
        
        # Default Tools Keys
        if graph_data.globalTools:
            for tool in graph_data.globalTools:
                if tool.requiresKey and tool.apiKey:
                    env_key = f"{tool.id.upper()}_API_KEY"
                    if tool.id == 'serper':
                        env_key = "SERPER_API_KEY"
                    env_lines.append(f"{env_key}={tool.apiKey}")
                    needed_keys.append(env_key)

        env_content = "\n".join(env_lines) + "\n"
        zip_file.writestr(f"{folder_name}/.env", env_content)

        # 1.5 Workspace Directory
        zip_file.writestr(f"{folder_name}/workspace/.gitkeep", "") # Create empty workspace dir

        # 2. pyproject.toml
        pyproject_content = f"""[project]
name = "{folder_name}"
version = "0.1.0"
description = "{project_name} - generated by Simple Crew Builder"
authors = [{{ name = "{author_name}", email = "{author_email}" }}]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai-tools[mcp]>=1.10.1",
    "crewai[google-genai,tools]>=1.10.1"
]

[project.scripts]
{folder_name} = "{folder_name}.main:run"
run_crew = "{folder_name}.main:run"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
"""
        zip_file.writestr(f"{folder_name}/pyproject.toml", pyproject_content)

        # 3. README.md
        desc_section = f"\n{project_description}\n" if project_description else ""
        keys_instructions = "\n".join([f"   - `{key}=sua_chave_aqui`" for key in needed_keys])
        readme_content = f"""# {project_name}
{desc_section}
Este projeto foi gerado automaticamente pelo **Simple Crew Builder**. Ele utiliza a estrutura moderna do CrewAI com suporte a MCP (Model Context Protocol).

## 🚀 Pré-requisitos

Para uma experiência otimizada, recomendamos o uso do gerenciador de pacotes **uv**.

### Como instalar o uv:

- **Windows:**
  ```powershell
  powershell -ExecutionPolicy ByPass -c "irt https://astral.sh/uv/install.ps1 | iex"
  ```
- **macOS / Linux:**
  ```bash
  curl -LsSf https://astral.sh/uv/install.sh | sh
  ```

## 🛠️ Como rodar o projeto

1. **Configuração de Ambiente:**
   - Crie/edite o arquivo `.env` na raiz do projeto e adicione suas chaves:
     ```env
{keys_instructions}
     ```

2. **Instalação de Dependências:**
   ```bash
   uv sync
   ```

3. **Execução:**
   ```bash
   uv run run_crew
   ```
   *Ou execute diretamente o arquivo principal:*
   ```bash
   uv run python src/{folder_name}/main.py
   ```

## 📂 Estrutura do Projeto

- `src/{folder_name}/config/`: Arquivos YAML de configuração para Agentes e Tarefas.
- `src/{folder_name}/crew.py`: Lógica principal de orquestração da Crew.
- `src/{folder_name}/main.py`: Ponto de entrada para execução e setup de MCP Tools.
- `src/{folder_name}/tools.py`: Ferramentas Python customizadas.
- `pyproject.toml`: Configurações de dependências e metadados.

---
Gerado com ❤️ por **Simple Crew Builder**
"""
        zip_file.writestr(f"{folder_name}/README.md", readme_content)

        # 4. Prepare data for YAMLs and Python (Sorted by Visual Hierarchy)
        nodes = {node.id: node for node in graph_data.nodes}
        
        all_agent_nodes = [n for n in graph_data.nodes if n.type == 'agent']
        all_task_nodes = [n for n in graph_data.nodes if n.type == 'task']
        crew_node = next((n for n in graph_data.nodes if n.type == 'crew'), None)

        # --- ORDENAÇÃO À PROVA DE BALAS (Sincronizada com crew_builder.py) ---
        
        # 1. Ordem dos Agentes (Hereditário da Crew)
        agent_order_hint = getattr(crew_node.data, 'agentOrder', []) if crew_node else []
        agent_ids_set = {n.id for n in all_agent_nodes}
        
        ordered_agent_ids = [aid for aid in agent_order_hint if aid in agent_ids_set]
        # Agentes que escaparam do agentOrder
        ordered_agent_ids.extend([n.id for n in all_agent_nodes if n.id not in set(ordered_agent_ids)])
        
        agent_nodes = [nodes[aid] for aid in ordered_agent_ids if aid in nodes]

        # 2. Agrupa as tasks por agente lendo as edges
        agent_to_tasks = {aid: [] for aid in ordered_agent_ids}
        for edge in graph_data.edges:
            if edge.source in agent_ids_set and nodes.get(edge.target) and nodes[edge.target].type == 'task':
                if edge.source in agent_to_tasks:
                    agent_to_tasks[edge.source].append(edge.target)
        
        base_task_queue = []
        for aid in ordered_agent_ids:
            tasks_of_agent = agent_to_tasks.get(aid, [])
            ag_node = nodes.get(aid)
            ag_task_order = getattr(ag_node.data, 'taskOrder', []) if ag_node else []
            
            # Prioridade para o taskOrder (ordem visual no card)
            for tid in ag_task_order:
                if tid in tasks_of_agent and tid not in base_task_queue:
                    base_task_queue.append(tid)
            # Tasks conectadas mas sem ordem explícita
            for tid in tasks_of_agent:
                if tid not in base_task_queue:
                    base_task_queue.append(tid)
        
        # Tasks órfãs (segurança)
        for n in all_task_nodes:
            if n.id not in base_task_queue:
                base_task_queue.append(n.id)
        
        # 3. Resolução de Grafo (Context Dependencies)
        final_task_ids_ordered = []
        visited = set()
        visiting = set()

        def resolve_task_dependencies(tid):
            if tid in visiting: return # Cycle protection
            if tid in visited: return
            visiting.add(tid)
            
            t_node = nodes.get(tid)
            if t_node:
                # Pre-requisitos (context) devem vir antes
                context_ids = getattr(t_node.data, 'context', []) or []
                for cid in context_ids:
                    resolve_task_dependencies(cid)
                
                final_task_ids_ordered.append(tid)
                visited.add(tid)
            visiting.remove(tid)

        for tid in base_task_queue:
            resolve_task_dependencies(tid)
        
        task_nodes = [nodes[tid] for tid in final_task_ids_ordered if tid in nodes]

        package_path = f"{folder_name}/src/{folder_name}"

        # 5. tools/ (Custom Tools folder)
        used_custom_tool_ids = set()
        for agent in agent_nodes:
            tool_ids = getattr(agent.data, 'customToolIds', []) or []
            for tid in tool_ids:
                used_custom_tool_ids.add(tid)
        
        for task in task_nodes:
            tool_ids = getattr(task.data, 'customToolIds', []) or []
            for tid in tool_ids:
                used_custom_tool_ids.add(tid)
        
        custom_tools_dict = {t.id: t for t in (graph_data.customTools or [])}
        has_custom_tools = False
        
        # Tools directory __init__.py
        tools_package_path = f"{package_path}/tools"
        
        for tid in used_custom_tool_ids:
            if tid in custom_tools_dict:
                tool_data = custom_tools_dict[tid]
                has_custom_tools = True
                
                # Slugify name for filename
                tool_slug = to_snake_case(tool_data.name)
                if not tool_slug:
                    tool_slug = f"tool_{tid[:8]}"
                
                # Standard imports for each tool file
                tool_file_content = "from crewai.tools import tool\nfrom pydantic import BaseModel, Field\nimport os\nimport json\n\n"
                
                # Verify if code already has @tool decorator
                has_decorator = "@tool" in tool_data.code
                
                if not has_decorator:
                    # Apply decorator with name from DB
                    name_for_decorator = tool_data.name.lower().replace(" ", "_")
                    # Localiza o primeiro 'def' ou 'class' para inserir o decorator logo antes dele
                    # Capturamos a indentação horizontal existente ([ \t]*)
                    match = re.search(r'^([ \t]*)(?:def|class)\s+', tool_data.code, re.MULTILINE)
                    if match:
                        indent = match.group(1)
                        decorator_code = f'{indent}@tool("{name_for_decorator}")\n'
                        start_pos = match.start()
                        tool_code_modified = tool_data.code[:start_pos] + decorator_code + tool_data.code[start_pos:]
                        tool_file_content += tool_code_modified + "\n"
                    else:
                        tool_file_content += f'@tool("{name_for_decorator}")\n' + tool_data.code + "\n"
                else:
                    tool_file_content += tool_data.code + "\n"
                
                zip_file.writestr(f"{tools_package_path}/{tool_slug}.py", tool_file_content)

        if has_custom_tools:
            # Add __init__.py to make it a package
            zip_file.writestr(f"{tools_package_path}/__init__.py", "# Custom tools package\n")

        # Coleta de Parâmetros (Placeholders)
        all_placeholders = set()

        # 6. src/config/agents.yaml
        agents_yaml_data = {}
        for node in agent_nodes:
            agent_key = to_snake_case(node.data.name) if node.data.name else f"agent_{node.id[:8]}"
            
            role = clean_text(node.data.role or "")
            goal = clean_text(node.data.goal or "")
            backstory = clean_text(node.data.backstory or "")
            
            all_placeholders.update(extract_placeholders(role))
            all_placeholders.update(extract_placeholders(goal))
            all_placeholders.update(extract_placeholders(backstory))

            # Exporter: Força o Agente a respeitar o Workspace (Caminho relativo padronizado para o export)
            workspace_instruction = "\n\nIMPORTANT: Your current working directory is './workspace'. All file operations MUST be relative to this path. Never write or read files outside of this directory."
            
            agent_data = {
                "role": BlockStr(role + "\n"),
                "goal": BlockStr(goal + "\n"),
                "backstory": BlockStr(backstory + workspace_instruction + "\n")
            }
            
            # Add LLM config if available
            if agent_llms and node.id in agent_llms:
                llm_info = agent_llms[node.id]
                agent_data["llm"] = llm_info["model"]
            
            agents_yaml_data[agent_key] = agent_data
        
        agents_yaml = yaml.dump(
            agents_yaml_data, 
            Dumper=yaml.SafeDumper, 
            allow_unicode=True, 
            sort_keys=False, 
            indent=2, 
            default_flow_style=False
        )
        zip_file.writestr(f"{package_path}/config/agents.yaml", agents_yaml)

        # 7. src/{folder_name}/config/tasks.yaml
        tasks_yaml_data = {}
        for node in task_nodes:
            task_key = to_snake_case(node.data.name) if node.data.name else f"task_{node.id[:8]}"
            
            description = clean_text(node.data.description or "")
            expected_output = clean_text(node.data.expected_output or "")
            
            all_placeholders.update(extract_placeholders(description))
            all_placeholders.update(extract_placeholders(expected_output))

            # Find assigned agent
            agent_id = next((e.source for e in graph_data.edges if e.target == node.id and nodes[e.source].type == 'agent'), None)
            agent_key = "default_agent"
            if agent_id:
                agent_node = nodes[agent_id]
                agent_key = to_snake_case(agent_node.data.name) if agent_node.data.name else f"agent_{agent_id[:8]}"

            # Exporter: Injeção de Prompt na Task
            workspace_task_instruction = "\n\nNOTE: All files must be handled within the workspace: './workspace'."
            
            tasks_yaml_data[task_key] = {
                "description": BlockStr(description + workspace_task_instruction + "\n"),
                "expected_output": BlockStr(expected_output + "\n"),
                "agent": agent_key # Keys and references stay plain
            }
        
        tasks_yaml = yaml.dump(
            tasks_yaml_data, 
            Dumper=yaml.SafeDumper, 
            allow_unicode=True, 
            sort_keys=False, 
            indent=2, 
            default_flow_style=False
        )
        zip_file.writestr(f"{package_path}/config/tasks.yaml", tasks_yaml)

        # 8. src/{folder_name}/crew.py
        class_name = f"{folder_name.title().replace('_', '')}Crew"
        crew_py_content = generate_crew_py(
            agent_nodes, 
            task_nodes, 
            crew_node, 
            graph_data.edges, 
            nodes, 
            class_name, 
            custom_tools_dict,
            graph_data.globalTools
        )
        zip_file.writestr(f"{package_path}/crew.py", crew_py_content)

        # 9. src/{folder_name}/main.py
        # Detecta placeholders nos YAMLs
        placeholders_from_yaml = {p: f"valor_para_{p}" for p in sorted(list(all_placeholders))}
        
        # Coleta inputs definidos manualmente no nó da Crew
        manual_inputs = {}
        if crew_node and hasattr(crew_node.data, 'inputs') and crew_node.data.inputs:
            manual_inputs = {k: v for k, v in crew_node.data.inputs.items() if not k.startswith('input_')}
        
        # Merge: Inputs manuais sobrescrevem placeholders automáticos
        final_inputs = {**placeholders_from_yaml, **manual_inputs}
        
        inputs_str = json.dumps(final_inputs, indent=8, ensure_ascii=False).replace('}', '        }')
        
        mcp_setup_code = ""
        mcp_import = ""
        if mcp_servers:
            mcp_import = "\nfrom contextlib import ExitStack\nfrom crewai_tools import MCPServerAdapter\nfrom mcp import StdioServerParameters"
            mcp_setup_code = "\n    mcp_tools = {}\n    with ExitStack() as stack:\n"
            for s in mcp_servers:
                mcp_setup_code += f"        # Setup {s['name']}\n"
                mcp_setup_code += f"        params_{to_snake_case(s['name'])} = StdioServerParameters(\n"
                mcp_setup_code += f"            command={json.dumps(s['command'])},\n"
                mcp_setup_code += f"            args={json.dumps(s['args']) or '[]'},\n"
                mcp_setup_code += f"            env={json.dumps(s['env_vars']) or 'None'}\n"
                mcp_setup_code += f"        )\n"
                mcp_setup_code += f"        mcp_tools['{s['id']}'] = stack.enter_context(MCPServerAdapter(params_{to_snake_case(s['name'])}))\n\n"
            
            mcp_setup_code += f"        {class_name}(mcp_tools=mcp_tools).crew().kickoff(inputs=inputs)\n"
        else:
            mcp_setup_code = f"    {class_name}().crew().kickoff(inputs=inputs)\n"

        main_py_content = f"""from {folder_name}.crew import {class_name}{mcp_import}

def run():
    # Parâmetros detectados nos arquivos YAML
    inputs = {inputs_str}
    
{mcp_setup_code}
if __name__ == "__main__":
    run()
"""
        zip_file.writestr(f"{package_path}/main.py", main_py_content)
        
        # 10. src/{folder_name}/__init__.py
        zip_file.writestr(f"{package_path}/__init__.py", "")
        # Adiciona __init__.py no src/
        zip_file.writestr(f"{folder_name}/src/__init__.py", "")

    return buffer.getvalue()

def generate_crew_py(agent_nodes, task_nodes, crew_node, edges, nodes, class_name, custom_tools_dict=None, global_tools_config=None) -> str:
    agents_methods = ""
    needed_tools_imports = []
    needed_crewai_tools = {"FileReadTool", "FileWriterTool"}
    
    global_configs = {t.id: t for t in (global_tools_config or [])}
    for node in agent_nodes:
        agent_key = to_snake_case(node.data.name) if node.data.name else f"agent_{node.id[:8]}"
        method_name = agent_key
        
        # Tools
        mcp_ids = getattr(node.data, 'mcpServerIds', []) or []
        custom_tool_ids = getattr(node.data, 'customToolIds', []) or []
        
        tools_list = []
        tools_code = ""

        # Setup Default Tools (globalTools)
        global_ids = getattr(node.data, 'globalToolIds', []) or []
        for gid in global_ids:
            config = global_configs.get(gid)
            if not config or not config.isEnabled:
                continue
            
            if gid == 'serper':
                tools_list.append("SerperDevTool()")
                needed_crewai_tools.add("SerperDevTool")
            elif gid == 'scrape':
                tools_list.append("ScrapeWebsiteTool()")
                needed_crewai_tools.add("ScrapeWebsiteTool")
            elif gid == 'directory_read':
                tools_list.append("DirectoryReadTool(directory='./workspace')")
                needed_crewai_tools.add("DirectoryReadTool")
            elif gid == 'file_read':
                tools_list.append("WorkspaceFileReadTool(workspace_path='./workspace')")
                needed_crewai_tools.add("FileReadTool")
            elif gid == 'file_write':
                tools_list.append("WorkspaceFileWriterTool(workspace_path='./workspace')")
                needed_crewai_tools.add("FileWriterTool")
            elif gid == 'directory_search':
                tools_list.append("DirectorySearchTool(directory='./workspace')")
                needed_crewai_tools.add("DirectorySearchTool")
            elif gid == 'pdf_search':
                tools_list.append("PDFSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("PDFSearchTool")
            elif gid == 'docx_search':
                tools_list.append("DOCXSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("DOCXSearchTool")
            elif gid == 'json_search':
                tools_list.append("JSONSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("JSONSearchTool")
            elif gid == 'xml_search':
                tools_list.append("XMLSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("XMLSearchTool")
            elif gid == 'csv_search':
                tools_list.append("CSVSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("CSVSearchTool")
            elif gid == 'mdx_search':
                tools_list.append("MDXSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("MDXSearchTool")
            elif gid == 'txt_search':
                tools_list.append("TXTSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("TXTSearchTool")
            elif gid == 'ocr':
                tools_list.append("OCRTool()")
                needed_crewai_tools.add("OCRTool")

        # Setup MCP tools
        if mcp_ids:
            tools_code += "        this_tools = []\n"
            for mid in mcp_ids:
                tools_code += f"        this_tools.extend(self.mcp_tools.get('{mid}', []))\n"
            tools_list.append("this_tools")

        # Setup Custom Tools
        if custom_tool_ids and custom_tools_dict:
            for cid in custom_tool_ids:
                if cid in custom_tools_dict:
                    tool_data = custom_tools_dict[cid]
                    tool_slug = to_snake_case(tool_data.name) or f"tool_{cid[:8]}"
                    
                    # Extract function name from code
                    match = re.search(r'def\s+([a-zA-Z0-9_]+)', tool_data.code)
                    if match:
                        func_name = match.group(1)
                        tools_list.append(func_name)
                        # Store info for imports: (slug, func_name)
                        if (tool_slug, func_name) not in needed_tools_imports:
                            needed_tools_imports.append((tool_slug, func_name))

        agents_methods += f"""
    @agent
    def {method_name}(self) -> Agent:
{tools_code if mcp_ids else ""}
        return Agent(
            config=self.agents_config['{agent_key}'],
            verbose=True{",\n            tools=[" + ", ".join(tools_list) + "]" if tools_list else ""}
        )
"""

    tasks_methods = ""
    for node in task_nodes:
        task_key = to_snake_case(node.data.name) if node.data.name else f"task_{node.id[:8]}"
        method_name = task_key
        
        # Tools (Default/Official)
        global_tool_ids = getattr(node.data, 'globalToolIds', []) or []
        task_tools_list = []
        
        for gid in global_tool_ids:
            if gid == 'serper':
                task_tools_list.append("SerperDevTool()")
                needed_crewai_tools.add("SerperDevTool")
            elif gid == 'scrape':
                task_tools_list.append("ScrapeWebsiteTool()")
                needed_crewai_tools.add("ScrapeWebsiteTool")
            elif gid == 'directory_read':
                task_tools_list.append("DirectoryReadTool(directory='./workspace')")
                needed_crewai_tools.add("DirectoryReadTool")
            elif gid == 'file_read':
                task_tools_list.append("WorkspaceFileReadTool(workspace_path='./workspace')")
                needed_crewai_tools.add("FileReadTool")
            elif gid == 'file_write':
                task_tools_list.append("WorkspaceFileWriterTool(workspace_path='./workspace')")
                needed_crewai_tools.add("FileWriterTool")
            elif gid == 'directory_search':
                task_tools_list.append("DirectorySearchTool(directory='./workspace')")
                needed_crewai_tools.add("DirectorySearchTool")
            elif gid == 'pdf_search':
                task_tools_list.append("PDFSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("PDFSearchTool")
            elif gid == 'docx_search':
                task_tools_list.append("DOCXSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("DOCXSearchTool")
            elif gid == 'json_search':
                task_tools_list.append("JSONSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("JSONSearchTool")
            elif gid == 'xml_search':
                task_tools_list.append("XMLSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("XMLSearchTool")
            elif gid == 'csv_search':
                task_tools_list.append("CSVSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("CSVSearchTool")
            elif gid == 'mdx_search':
                task_tools_list.append("MDXSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("MDXSearchTool")
            elif gid == 'txt_search':
                task_tools_list.append("TXTSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("TXTSearchTool")
            elif gid == 'ocr':
                task_tools_list.append("OCRTool()")
                needed_crewai_tools.add("OCRTool")

        # Custom Tools
        custom_tool_ids = getattr(node.data, 'customToolIds', []) or []
        
        if custom_tool_ids and custom_tools_dict:
            for cid in custom_tool_ids:
                if cid in custom_tools_dict:
                    tool_data = custom_tools_dict[cid]
                    tool_slug = to_snake_case(tool_data.name) or f"tool_{cid[:8]}"
                    
                    # Extract function name from code
                    match = re.search(r'def\s+([a-zA-Z0-9_]+)', tool_data.code)
                    if match:
                        func_name = match.group(1)
                        task_tools_list.append(func_name)
                        # Store info for imports: (slug, func_name)
                        if (tool_slug, func_name) not in needed_tools_imports:
                            needed_tools_imports.append((tool_slug, func_name))

        # Build context
        context_ids = getattr(node.data, 'context', []) or []
        context_line = ""
        if context_ids:
            context_methods = []
            for cid in context_ids:
                # Find node in the nodes dict
                cnode = nodes.get(cid)
                
                if cnode:
                    ckey = to_snake_case(cnode.data.name) if cnode.data.name else f"task_{cid[:8]}"
                    context_methods.append(f"self.{ckey}()")
            if context_methods:
                context_line = f",\n            context=[{', '.join(context_methods)}]"

        tasks_methods += f"""
    @task
    def {method_name}(self) -> Task:
        return Task(
            config=self.tasks_config['{task_key}']{context_line}{",\n            tools=[" + ", ".join(task_tools_list) + "]" if task_tools_list else ""}
        )
"""

    process_type = "Process.sequential"
    if crew_node and getattr(crew_node.data, 'process', None) == "hierarchical":
        process_type = "Process.hierarchical"

    tools_import = ""
    if needed_tools_imports:
        for slug, func in needed_tools_imports:
            tools_import += f"\nfrom .tools.{slug} import {func}"

    crewai_tools_import = ""
    if needed_crewai_tools:
        crewai_tools_import = f"\nfrom crewai_tools import {', '.join(sorted(list(needed_crewai_tools)))}"

    content = f"""from crewai import Agent, Crew, Process, Task
from crewai.project import CrewBase, agent, crew, task{crewai_tools_import}{tools_import}
from pydantic import Field
import os
from typing import Any

# --- WORKSPACE AWARE FILE TOOLS ---
class WorkspaceFileReadTool(FileReadTool):
    workspace_path: str = Field(..., description="The root path of the workspace")
    
    def _run(self, **kwargs: Any) -> str:
        file_path = kwargs.get('file_path') or self.file_path
        if file_path:
            abs_workspace = os.path.abspath(self.workspace_path)
            if not os.path.isabs(file_path):
                file_path = os.path.join(abs_workspace, file_path)
            kwargs['file_path'] = file_path
        return super()._run(**kwargs)

class WorkspaceFileWriterTool(FileWriterTool):
    workspace_path: str = Field(..., description="The root path of the workspace")
    
    def _run(self, **kwargs: Any) -> str:
        requested_dir = kwargs.get('directory')
        abs_workspace = os.path.abspath(self.workspace_path)
        if not requested_dir or not os.path.isabs(requested_dir):
            if not requested_dir or requested_dir == "./":
                kwargs['directory'] = abs_workspace
            else:
                kwargs['directory'] = os.path.join(abs_workspace, requested_dir.lstrip('./\\\\'))
        return super()._run(**kwargs)

@CrewBase
class {class_name}():
    \"\"\"Orquestração de agentes gerada pelo SimpleCrew\"\"\"
    agents_config = 'config/agents.yaml'
    tasks_config = 'config/tasks.yaml'

    def __init__(self, mcp_tools=None):
        self.mcp_tools = mcp_tools or {{}}

    {agents_methods}
    {tasks_methods}

    @crew
    def crew(self) -> Crew:
        \"\"\"Cria a Crew com os agentes e tarefas definidos\"\"\"
        return Crew(
            agents=self.agents,
            tasks=self.tasks,
            process={process_type},
            verbose=True
        )
"""
    return content
