import yaml
import zipfile
import io
import re
import json
import os
from typing import List, Dict, Any, Optional, Annotated, Union
from .schemas import GraphData, Node, Edge


import unicodedata

class BlockStr(str):
    """Marcador para strings que devem ser renderizadas como bloco (>) no YAML"""

def block_str_representer(dumper, data):
    return dumper.represent_scalar(u'tag:yaml.org,2002:str', data, style='>')

# Registra o representer globalmente para o SafeDumper
yaml.SafeDumper.add_representer(BlockStr, block_str_representer)

def normalize_text(text: str) -> str:
    """Remove acentos e caracteres especiais para nomes de arquivos/chaves"""
    if not text: return ""
    return "".join(c for c in unicodedata.normalize('NFD', text) if unicodedata.category(c) != 'Mn')

def to_snake_case(text: str) -> str:
    if not text:
        return ""
    # Remove acentos
    text = normalize_text(text)
    # Converte CamelCase para snake_case
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', text)
    s2 = re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()
    # Troca espaços e hífens por underscore
    s3 = s2.replace(" ", "_").replace("-", "_")
    # Remove caracteres não alfanuméricos exceto underscore
    s4 = re.sub(r'[^a-z0-9_]', '', s3)
    # Remove múltiplos underscores seguidos
    return re.sub(r'_+', '_', s4).strip('_')

def clean_text(text: str) -> str:
    """Normaliza o texto para uma única linha (sem quebras) para que o YAML realize a dobra (folding) de forma limpa"""
    if not text: return ""
    # Remove qualquer sequência de espaços ou quebras de linha e substitui por um único espaço
    return " ".join(text.split()).strip()

def extract_placeholders(text: str) -> List[str]:
    """Extrai nomes de variáveis entre chaves {variavel}"""
    if not text:
        return []
    return re.findall(r'\{([a-zA-Z0-9_]+)\}', text)

def generate_python_project(graph_data: GraphData, project_name: str, author_name: str = "SimpleCrew", author_email: str = "admin@simplecrew.ai", mcp_servers: List[Dict[str, Any]] = None, project_description: str = "", agent_llms: Dict[str, Dict[str, Any]] = None, providers: List[str] = None, workspace_path: str = None) -> bytes:
    """
    Transforma GraphData em um arquivo ZIP contendo um projeto CrewAI completo.
    """
    # Sanitização básica do nome do projeto para pastas
    folder_name = to_snake_case(project_name)
    if not folder_name:
        folder_name = "my_crew_project"

    buffer = io.BytesIO()
    
    with zipfile.ZipFile(buffer, 'a', zipfile.ZIP_DEFLATED, False) as zip_file:
        # 1. .env
        env_lines = []
        needed_keys = []
        providers = providers or ["openai"]
        if "openai" in providers:
            env_lines.append("OPENAI_API_KEY=your_openai_api_key_here")
            needed_keys.append("OPENAI_API_KEY")
        if "anthropic" in providers:
            env_lines.append("ANTHROPIC_API_KEY=your_anthropic_api_key_here")
            needed_keys.append("ANTHROPIC_API_KEY")
        if "google" in providers:
            env_lines.append("GOOGLE_API_KEY=your_google_api_key_here")
            needed_keys.append("GOOGLE_API_KEY")
        if "groq" in providers:
            env_lines.append("GROQ_API_KEY=your_groq_api_key_here")
            needed_keys.append("GROQ_API_KEY")
        
        # Default Tools Keys
        if graph_data.globalTools:
            for tool in graph_data.globalTools:
                if tool.requiresKey and tool.apiKey:
                    env_key = f"{tool.id.upper()}_API_KEY"
                    if tool.id == 'serper':
                        env_key = "SERPER_API_KEY"
                    env_lines.append(f"{env_key}={tool.apiKey}")
                    needed_keys.append(env_key)

        env_content = "\n".join(env_lines) + "\n"
        zip_file.writestr(f"{folder_name}/.env", env_content)

        # 1.5 Workspace Directory
        zip_file.writestr(f"{folder_name}/workspace/.gitkeep", "") # Create empty workspace dir

        # 2. pyproject.toml
        pyproject_content = f"""[project]
name = "{folder_name}"
version = "0.1.0"
description = "{project_name} - generated by Simple Crew Builder"
authors = [{{ name = "{author_name}", email = "{author_email}" }}]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai-tools[mcp]>=1.10.1",
    "crewai[google-genai,tools]>=1.10.1"
]

[project.scripts]
{folder_name} = "{folder_name}.main:run"
run_crew = "{folder_name}.main:run"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
"""
        zip_file.writestr(f"{folder_name}/pyproject.toml", pyproject_content)

        # 3. README.md
        desc_section = f"\n{project_description}\n" if project_description else ""
        keys_instructions = "\n".join([f"   - `{key}=sua_chave_aqui`" for key in needed_keys])
        readme_content = f"""# {project_name}
{desc_section}
Este projeto foi gerado automaticamente pelo **Simple Crew Builder**. Ele utiliza a estrutura moderna do CrewAI com suporte a MCP (Model Context Protocol).

## 🚀 Pré-requisitos

Para uma experiência otimizada, recomendamos o uso do gerenciador de pacotes **uv**.

### Como instalar o uv:

- **Windows:**
  ```powershell
  powershell -ExecutionPolicy ByPass -c "irt https://astral.sh/uv/install.ps1 | iex"
  ```
- **macOS / Linux:**
  ```bash
  curl -LsSf https://astral.sh/uv/install.sh | sh
  ```

## 🛠️ Como rodar o projeto

1. **Configuração de Ambiente:**
   - Crie/edite o arquivo `.env` na raiz do projeto e adicione suas chaves:
     ```env
{keys_instructions}
     ```

2. **Instalação de Dependências:**
   ```bash
   uv sync
   ```

3. **Execução:**
   ```bash
   uv run run_crew
   ```
   *Ou execute diretamente o arquivo principal:*
   ```bash
   uv run python src/{folder_name}/main.py
   ```

## 📂 Estrutura do Projeto

- `src/{folder_name}/config/`: Arquivos YAML de configuração para Agentes e Tarefas.
- `src/{folder_name}/crew.py`: Lógica principal de orquestração da Crew.
- `src/{folder_name}/main.py`: Ponto de entrada para execução e setup de MCP Tools.
- `src/{folder_name}/tools.py`: Ferramentas Python customizadas.
- `pyproject.toml`: Configurações de dependências e metadados.

---
Gerado com ❤️ por **Simple Crew Builder**
"""
        zip_file.writestr(f"{folder_name}/README.md", readme_content)

        # 4. Prepare data for YAMLs and Python (Sorted by Visual Hierarchy)
        nodes = {node.id: node for node in graph_data.nodes}
        
        all_agent_nodes = [n for n in graph_data.nodes if n.type == 'agent']
        all_task_nodes = [n for n in graph_data.nodes if n.type == 'task']
        crew_node = next((n for n in graph_data.nodes if n.type == 'crew'), None)

        # --- ORDENAÇÃO À PROVA DE BALAS (Sincronizada com crew_builder.py) ---
        
        # 1. Ordem dos Agentes (Hereditário da Crew)
        agent_order_hint = getattr(crew_node.data, 'agentOrder', []) if crew_node else []
        agent_ids_set = {n.id for n in all_agent_nodes}
        
        ordered_agent_ids = [aid for aid in agent_order_hint if aid in agent_ids_set]
        # Agentes que escaparam do agentOrder
        ordered_agent_ids.extend([n.id for n in all_agent_nodes if n.id not in set(ordered_agent_ids)])
        
        agent_nodes = [nodes[aid] for aid in ordered_agent_ids if aid in nodes]

        # 2. Agrupa as tasks por agente lendo as edges
        agent_to_tasks = {aid: [] for aid in ordered_agent_ids}
        for edge in graph_data.edges:
            if edge.source in agent_ids_set and nodes.get(edge.target) and nodes[edge.target].type == 'task':
                if edge.source in agent_to_tasks:
                    agent_to_tasks[edge.source].append(edge.target)
        
        base_task_queue = []
        for aid in ordered_agent_ids:
            tasks_of_agent = agent_to_tasks.get(aid, [])
            ag_node = nodes.get(aid)
            ag_task_order = getattr(ag_node.data, 'taskOrder', []) if ag_node else []
            
            # Prioridade para o taskOrder (ordem visual no card)
            for tid in ag_task_order:
                if tid in tasks_of_agent and tid not in base_task_queue:
                    base_task_queue.append(tid)
            # Tasks conectadas mas sem ordem explícita
            for tid in tasks_of_agent:
                if tid not in base_task_queue:
                    base_task_queue.append(tid)
        
        # Tasks órfãs (segurança)
        for n in all_task_nodes:
            if n.id not in base_task_queue:
                base_task_queue.append(n.id)
        
        # 3. Resolução de Grafo (Context Dependencies)
        final_task_ids_ordered = []
        visited = set()
        visiting = set()

        def resolve_task_dependencies(tid):
            if tid in visiting: return # Cycle protection
            if tid in visited: return
            visiting.add(tid)
            
            t_node = nodes.get(tid)
            if t_node:
                # Pre-requisitos (context) devem vir antes
                context_ids = getattr(t_node.data, 'context', []) or []
                for cid in context_ids:
                    resolve_task_dependencies(cid)
                
                final_task_ids_ordered.append(tid)
                visited.add(tid)
            visiting.remove(tid)

        for tid in base_task_queue:
            resolve_task_dependencies(tid)
        
        task_nodes = [nodes[tid] for tid in final_task_ids_ordered if tid in nodes]

        package_path = f"{folder_name}/src/{folder_name}"

        # 5. tools/ (Custom Tools folder)
        used_custom_tool_ids = set()
        for agent in agent_nodes:
            tool_ids = getattr(agent.data, 'customToolIds', []) or []
            for tid in tool_ids:
                used_custom_tool_ids.add(tid)
        
        for task in task_nodes:
            tool_ids = getattr(task.data, 'customToolIds', []) or []
            for tid in tool_ids:
                used_custom_tool_ids.add(tid)
        
        custom_tools_dict = {t.id: t for t in (graph_data.customTools or [])}
        has_custom_tools = False
        
        # Tools directory __init__.py
        tools_package_path = f"{package_path}/tools"
        
        for tid in used_custom_tool_ids:
            if tid in custom_tools_dict:
                tool_data = custom_tools_dict[tid]
                has_custom_tools = True
                
                # Slugify name for filename
                tool_slug = to_snake_case(tool_data.name)
                if not tool_slug:
                    tool_slug = f"tool_{tid[:8]}"
                
                # Standard imports for each tool file
                tool_file_content = "from crewai.tools import tool\nfrom pydantic import BaseModel, Field\nimport os\nimport json\n\n"
                
                # Verify if code already has @tool decorator
                has_decorator = "@tool" in tool_data.code
                
                if not has_decorator:
                    # Apply decorator with name from DB
                    name_for_decorator = tool_data.name.lower().replace(" ", "_")
                    # Localiza o primeiro 'def' ou 'class' para inserir o decorator logo antes dele
                    # Capturamos a indentação horizontal existente ([ \t]*)
                    match = re.search(r'^([ \t]*)(?:def|class)\s+', tool_data.code, re.MULTILINE)
                    if match:
                        indent = match.group(1)
                        decorator_code = f'{indent}@tool("{name_for_decorator}")\n'
                        start_pos = match.start()
                        tool_code_modified = tool_data.code[:start_pos] + decorator_code + tool_data.code[start_pos:]
                        tool_file_content += tool_code_modified + "\n"
                    else:
                        tool_file_content += f'@tool("{name_for_decorator}")\n' + tool_data.code + "\n"
                else:
                    tool_file_content += tool_data.code + "\n"
                
                zip_file.writestr(f"{tools_package_path}/{tool_slug}.py", tool_file_content)

            # Add __init__.py to make it a package
            zip_file.writestr(f"{tools_package_path}/__init__.py", "# Custom tools package\n")

        # 5.5 utils.py (Common utilities for exported project)
        utils_content = """import os

def normalize_command(command: str) -> str:
    \"\"\"
    Normaliza o comando baseado no sistema operacional atual.
    \"\"\"
    if not command:
        return command
    
    is_windows = os.name == "nt"
    
    if command.lower() in ["npx", "npm"]:
        if is_windows:
            return f"{command}.cmd"
        return command
        
    if not is_windows:
        if command.lower().endswith(".cmd") or command.lower().endswith(".exe"):
            return os.path.splitext(command)[0]
    
    return command
"""
        zip_file.writestr(f"{package_path}/utils.py", utils_content)

        # Coleta de Parâmetros (Placeholders)
        all_placeholders = set()

        # 6. src/config/agents.yaml
        agents_yaml_data = {}
        for node in agent_nodes:
            agent_key = to_snake_case(node.data.name) if node.data.name else f"agent_{node.id[:8]}"
            
            role = clean_text(node.data.role or "")
            goal = clean_text(node.data.goal or "")
            backstory = clean_text(node.data.backstory or "")
            
            all_placeholders.update(extract_placeholders(role))
            all_placeholders.update(extract_placeholders(goal))
            all_placeholders.update(extract_placeholders(backstory))

            # Exporter: Força o Agente a respeitar o Workspace (Caminho relativo padronizado para o export)
            workspace_instruction = "\n\nIMPORTANT: Your current working directory is './workspace'. All file operations MUST be relative to this path. Never write or read files outside of this directory."
            
            agent_data = {
                "role": BlockStr(role + "\n"),
                "goal": BlockStr(goal + "\n"),
                "backstory": BlockStr(backstory + workspace_instruction + "\n")
            }
            
            # Add LLM config if available
            if agent_llms and node.id in agent_llms:
                llm_info = agent_llms[node.id]
                agent_data["llm"] = llm_info["model"]
            
            agents_yaml_data[agent_key] = agent_data
        
        agents_yaml = yaml.dump(
            agents_yaml_data, 
            Dumper=yaml.SafeDumper, 
            allow_unicode=True, 
            sort_keys=False, 
            indent=2, 
            default_flow_style=False
        )
        zip_file.writestr(f"{package_path}/config/agents.yaml", agents_yaml)

        # 7. src/{folder_name}/config/tasks.yaml
        tasks_yaml_data = {}
        for node in task_nodes:
            task_key = to_snake_case(node.data.name) if node.data.name else f"task_{node.id[:8]}"
            
            description = clean_text(node.data.description or "")
            expected_output = clean_text(node.data.expected_output or "")
            
            all_placeholders.update(extract_placeholders(description))
            all_placeholders.update(extract_placeholders(expected_output))

            # Find assigned agent
            agent_id = next((e.source for e in graph_data.edges if e.target == node.id and nodes[e.source].type == 'agent'), None)
            agent_key = "default_agent"
            if agent_id:
                agent_node = nodes[agent_id]
                agent_key = to_snake_case(agent_node.data.name) if agent_node.data.name else f"agent_{agent_id[:8]}"

            # Exporter: Injeção de Prompt na Task
            workspace_task_instruction = "\n\nNOTE: All files must be handled within the workspace: './workspace'."
            
            tasks_yaml_data[task_key] = {
                "description": BlockStr(description + workspace_task_instruction + "\n"),
                "expected_output": BlockStr(expected_output + "\n"),
                "agent": agent_key # Keys and references stay plain
            }
        
        tasks_yaml = yaml.dump(
            tasks_yaml_data, 
            Dumper=yaml.SafeDumper, 
            allow_unicode=True, 
            sort_keys=False, 
            indent=2, 
            default_flow_style=False
        )
        zip_file.writestr(f"{package_path}/config/tasks.yaml", tasks_yaml)

        # 8. src/{folder_name}/crew.py
        class_name = f"{folder_name.title().replace('_', '')}Crew"
        crew_py_content = generate_crew_py(
            agent_nodes, 
            task_nodes, 
            crew_node, 
            graph_data.edges, 
            nodes, 
            class_name, 
            custom_tools_dict,
            graph_data.globalTools,
            agent_llms
        )
        zip_file.writestr(f"{package_path}/crew.py", crew_py_content)

        # 9. src/{folder_name}/main.py
        # Detecta placeholders nos YAMLs
        placeholders_from_yaml = {p: f"valor_para_{p}" for p in sorted(list(all_placeholders))}
        
        # Coleta inputs definidos manualmente no nó da Crew
        manual_inputs = {}
        if crew_node and hasattr(crew_node.data, 'inputs') and crew_node.data.inputs:
            manual_inputs = {k: v for k, v in crew_node.data.inputs.items() if not k.startswith('input_')}
        
        # Merge: Inputs manuais sobrescrevem placeholders automáticos
        final_inputs = {**placeholders_from_yaml, **manual_inputs}
        
        inputs_str = json.dumps(final_inputs, indent=8, ensure_ascii=False).replace('}', '        }')
        
        mcp_setup_code = ""
        mcp_import = ""
        if mcp_servers:
            mcp_import = "\nfrom contextlib import ExitStack\nfrom crewai_tools import MCPServerAdapter\nfrom mcp import StdioServerParameters\nfrom .utils import normalize_command"
            mcp_setup_code = "\n    mcp_tools = {}\n    with ExitStack() as stack:\n"
            for s in mcp_servers:
                mcp_setup_code += f"        # Setup {s['name']}\n"
                mcp_setup_code += f"        params_{to_snake_case(s['name'])} = StdioServerParameters(\n"
                mcp_setup_code += f"            command=normalize_command({json.dumps(s['command'])}) if {json.dumps(s['command'])} else None,\n"
                mcp_setup_code += f"            args={json.dumps(s['args']) or '[]'},\n"
                mcp_setup_code += f"            env={json.dumps(s['env_vars']) or 'None'}\n"
                mcp_setup_code += f"        )\n"
                mcp_setup_code += f"        mcp_tools['{s['id']}'] = stack.enter_context(MCPServerAdapter(params_{to_snake_case(s['name'])}))\n\n"
            
            mcp_setup_code += f"        {class_name}(mcp_tools=mcp_tools).crew().kickoff(inputs=inputs)\n"
        else:
            mcp_setup_code = f"    {class_name}().crew().kickoff(inputs=inputs)\n"

        main_py_content = f"""from {folder_name}.crew import {class_name}{mcp_import}

def run():
    # Parâmetros detectados nos arquivos YAML
    inputs = {inputs_str}
    
{mcp_setup_code}
if __name__ == "__main__":
    run()
"""
        zip_file.writestr(f"{package_path}/main.py", main_py_content)
        
        # 10. src/{folder_name}/__init__.py
        zip_file.writestr(f"{package_path}/__init__.py", "")
        # Adiciona __init__.py no src/
        zip_file.writestr(f"{folder_name}/src/__init__.py", "")

    return buffer.getvalue()

def generate_crew_py(agent_nodes, task_nodes, crew_node, edges, nodes, class_name, custom_tools_dict=None, global_tools_config=None, agent_llms=None) -> str:
    agents_methods = ""
    needed_tools_imports = []
    needed_crewai_tools = {"FileReadTool", "FileWriterTool"}
    
    global_configs = {t.id: t for t in (global_tools_config or [])}
    for node in agent_nodes:
        agent_key = to_snake_case(node.data.name) if node.data.name else f"agent_{node.id[:8]}"
        method_name = agent_key
        
        # Tools
        mcp_ids = getattr(node.data, 'mcpServerIds', []) or []
        custom_tool_ids = getattr(node.data, 'customToolIds', []) or []
        
        tools_list = []
        tools_code = ""

        # Setup Default Tools (globalTools)
        global_ids = getattr(node.data, 'globalToolIds', []) or []
        for entry in global_ids:
            gid = entry
            if isinstance(entry, dict):
                gid = entry.get("id")
            
            if not gid:
                continue

            config = global_configs.get(gid)
            if not config or not config.isEnabled:
                continue
            
            if gid == 'serper':
                tools_list.append("SerperDevTool()")
                needed_crewai_tools.add("SerperDevTool")
            elif gid == 'scrape':
                tools_list.append("ScrapeWebsiteTool()")
                needed_crewai_tools.add("ScrapeWebsiteTool")
            elif gid == 'directory_read':
                tools_list.append("DirectoryReadTool(directory='./workspace')")
                needed_crewai_tools.add("DirectoryReadTool")
            elif gid == 'file_read':
                tools_list.append("WorkspaceFileReadTool(workspace_path='./workspace')")
                needed_crewai_tools.add("FileReadTool")
            elif gid == 'file_write':
                tools_list.append("WorkspaceFileWriterTool(workspace_path='./workspace')")
                needed_crewai_tools.add("FileWriterTool")
            elif gid == 'directory_search':
                tools_list.append("DirectorySearchTool(directory='./workspace')")
                needed_crewai_tools.add("DirectorySearchTool")
            elif gid == 'pdf_search':
                tools_list.append("PDFSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("PDFSearchTool")
            elif gid == 'docx_search':
                tools_list.append("DOCXSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("DOCXSearchTool")
            elif gid == 'json_search':
                tools_list.append("JSONSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("JSONSearchTool")
            elif gid == 'xml_search':
                tools_list.append("XMLSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("XMLSearchTool")
            elif gid == 'csv_search':
                tools_list.append("CSVSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("CSVSearchTool")
            elif gid == 'mdx_search':
                tools_list.append("MDXSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("MDXSearchTool")
            elif gid == 'txt_search':
                tools_list.append("TXTSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("TXTSearchTool")
            elif gid == 'ocr':
                tools_list.append("OCRTool()")
                needed_crewai_tools.add("OCRTool")

        # Setup MCP tools
        if mcp_ids:
            tools_code += "        this_tools = []\n"
            for mid in mcp_ids:
                tools_code += f"        this_tools.extend(self.mcp_tools.get('{mid}', []))\n"
            tools_list.append("this_tools")

        # Setup Custom Tools
        if custom_tool_ids and custom_tools_dict:
            for cid in custom_tool_ids:
                if cid in custom_tools_dict:
                    tool_data = custom_tools_dict[cid]
                    tool_slug = to_snake_case(tool_data.name) or f"tool_{cid[:8]}"
                    
                    # Extract function name from code
                    match = re.search(r'def\s+([a-zA-Z0-9_]+)', tool_data.code)
                    if match:
                        func_name = match.group(1)
                        tools_list.append(func_name)
                        # Store info for imports: (slug, func_name)
                        if (tool_slug, func_name) not in needed_tools_imports:
                            needed_tools_imports.append((tool_slug, func_name))

        # Options Settings
        agent_kwargs = [
            f"config=self.agents_config['{agent_key}']"
        ]
        
        if hasattr(node, 'data'):
            data = node.data
            if getattr(data, 'verbose', True) is False:
                agent_kwargs.append("verbose=False")
            else:
                agent_kwargs.append("verbose=True")
                
            if getattr(data, 'allow_delegation', False) is True:
                agent_kwargs.append("allow_delegation=True")
                
            if getattr(data, 'cache', True) is False:
                agent_kwargs.append("cache=False")
                
            if getattr(data, 'allow_code_execution', False) is True:
                agent_kwargs.append("allow_code_execution=True")
                
            if getattr(data, 'respect_context_window', True) is False:
                agent_kwargs.append("respect_context_window=False")
                
            if getattr(data, 'use_system_prompt', True) is False:
                agent_kwargs.append("use_system_prompt=False")
                
            max_iter = getattr(data, 'max_iter', None)
            if max_iter is not None and max_iter != 25:
                agent_kwargs.append(f"max_iter={max_iter}")
                
            max_retry_limit = getattr(data, 'max_retry_limit', None)
            if max_retry_limit is not None and max_retry_limit != 2:
                agent_kwargs.append(f"max_retry_limit={max_retry_limit}")
                
            max_rpm = getattr(data, 'max_rpm', None)
            if max_rpm is not None:
                agent_kwargs.append(f"max_rpm={max_rpm}")
                
            max_exec_time = getattr(data, 'max_execution_time', None)
            if max_exec_time is not None:
                agent_kwargs.append(f"max_execution_time={max_exec_time}")
                
            code_exec_mode = getattr(data, 'code_execution_mode', None)
            if code_exec_mode in ("safe", "unsafe") and getattr(data, 'allow_code_execution', False):
                agent_kwargs.append(f"code_execution_mode='{code_exec_mode}'")
                
            if getattr(data, 'reasoning', False) is True:
                agent_kwargs.append("reasoning=True")
                
            if getattr(data, 'multimodal', False) is True:
                agent_kwargs.append("multimodal=True")
                
            if getattr(data, 'inject_date', False) is True:
                agent_kwargs.append("inject_date=True")
                
            max_reasoning = getattr(data, 'max_reasoning_attempts', None)
            if max_reasoning is not None:
                agent_kwargs.append(f"max_reasoning_attempts={max_reasoning}")
                
            date_format = getattr(data, 'date_format', None)
            if date_format:
                agent_kwargs.append(f"date_format='{date_format}'")
                
            for tpl in ['system_template', 'prompt_template', 'response_template']:
                tpl_val = getattr(data, tpl, None)
                if tpl_val:
                    # Escape trillas to avoid syntax errors
                    escaped_tpl = tpl_val.replace('"""', '\\"\\"\\"')
                    agent_kwargs.append(f"{tpl}=\"\"\"{escaped_tpl}\"\"\"")
                    
                
        if agent_llms and getattr(node, 'id', None):
            fc_llm = agent_llms.get(f"function_calling_{node.id}")
            if fc_llm:
                agent_kwargs.append(f"function_calling_llm='{fc_llm['model']}'")

        if tools_list:
            agent_kwargs.append(f"tools=[{', '.join(tools_list)}]")
            
        agent_kwargs_str = ",\n            ".join(agent_kwargs)

        agents_methods += f"""
    @agent
    def {method_name}(self) -> Agent:
{tools_code if mcp_ids else ""}
        return Agent(
            {agent_kwargs_str}
        )
"""

    tasks_methods = ""
    for node in task_nodes:
        task_key = to_snake_case(node.data.name) if node.data.name else f"task_{node.id[:8]}"
        method_name = task_key
        
        # Tools (Default/Official)
        global_tool_ids = getattr(node.data, 'globalToolIds', []) or []
        task_tools_list = []
        
        for entry in global_tool_ids:
            gid = entry
            if isinstance(entry, dict):
                gid = entry.get("id")
            
            if not gid:
                continue

            if gid == 'serper':
                task_tools_list.append("SerperDevTool()")
                needed_crewai_tools.add("SerperDevTool")
            elif gid == 'scrape':
                task_tools_list.append("ScrapeWebsiteTool()")
                needed_crewai_tools.add("ScrapeWebsiteTool")
            elif gid == 'directory_read':
                task_tools_list.append("DirectoryReadTool(directory='./workspace')")
                needed_crewai_tools.add("DirectoryReadTool")
            elif gid == 'file_read':
                task_tools_list.append("WorkspaceFileReadTool(workspace_path='./workspace')")
                needed_crewai_tools.add("FileReadTool")
            elif gid == 'file_write':
                task_tools_list.append("WorkspaceFileWriterTool(workspace_path='./workspace')")
                needed_crewai_tools.add("FileWriterTool")
            elif gid == 'directory_search':
                task_tools_list.append("DirectorySearchTool(directory='./workspace')")
                needed_crewai_tools.add("DirectorySearchTool")
            elif gid == 'pdf_search':
                task_tools_list.append("PDFSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("PDFSearchTool")
            elif gid == 'docx_search':
                task_tools_list.append("DOCXSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("DOCXSearchTool")
            elif gid == 'json_search':
                task_tools_list.append("JSONSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("JSONSearchTool")
            elif gid == 'xml_search':
                task_tools_list.append("XMLSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("XMLSearchTool")
            elif gid == 'csv_search':
                task_tools_list.append("CSVSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("CSVSearchTool")
            elif gid == 'mdx_search':
                task_tools_list.append("MDXSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("MDXSearchTool")
            elif gid == 'txt_search':
                task_tools_list.append("TXTSearchTool(config={'directory': './workspace'})")
                needed_crewai_tools.add("TXTSearchTool")
            elif gid == 'ocr':
                task_tools_list.append("OCRTool()")
                needed_crewai_tools.add("OCRTool")

        # Custom Tools
        custom_tool_ids = getattr(node.data, 'customToolIds', []) or []
        
        if custom_tool_ids and custom_tools_dict:
            for cid in custom_tool_ids:
                if cid in custom_tools_dict:
                    tool_data = custom_tools_dict[cid]
                    tool_slug = to_snake_case(tool_data.name) or f"tool_{cid[:8]}"
                    
                    # Extract function name from code
                    match = re.search(r'def\s+([a-zA-Z0-9_]+)', tool_data.code)
                    if match:
                        func_name = match.group(1)
                        task_tools_list.append(func_name)
                        # Store info for imports: (slug, func_name)
                        if (tool_slug, func_name) not in needed_tools_imports:
                            needed_tools_imports.append((tool_slug, func_name))

        # Build context
        context_ids = getattr(node.data, 'context', []) or []
        context_line = ""
        if context_ids:
            context_methods = []
            for cid in context_ids:
                # Find node in the nodes dict
                cnode = nodes.get(cid)
                
                if cnode:
                    ckey = to_snake_case(cnode.data.name) if cnode.data.name else f"task_{cid[:8]}"
                    context_methods.append(f"self.{ckey}()")
            if context_methods:
                context_line = f",\n            context=[{', '.join(context_methods)}]"

        task_kwargs = [f"config=self.tasks_config['{task_key}']"]
        if context_line:
            task_kwargs.append(f"context=[{', '.join(context_methods)}]")
        if task_tools_list:
            task_kwargs.append(f"tools=[{', '.join(task_tools_list)}]")
            
        if getattr(node.data, 'async_execution', False) is True:
            task_kwargs.append("async_execution=True")
            
        if getattr(node.data, 'human_input', False) is True:
            task_kwargs.append("human_input=True")
            
        if getattr(node.data, 'create_directory', True) is False:
            task_kwargs.append("create_directory=False")
            
        output_file = getattr(node.data, 'output_file', None)
        if output_file:
            task_kwargs.append(f"output_file='{output_file}'")
            
        task_kwargs_str = ",\n            ".join(task_kwargs)

        tasks_methods += f"""
    @task
    def {method_name}(self) -> Task:
        return Task(
            {task_kwargs_str}
        )
"""

    process_type = "Process.sequential"
    if crew_node and getattr(crew_node.data, 'process', None) == "hierarchical":
        process_type = "Process.hierarchical"

    crew_kwargs = [
        "agents=self.agents",
        "tasks=self.tasks",
        f"process={process_type}"
    ]

    if crew_node:
        data = crew_node.data
        if getattr(data, 'verbose', True) is False:
            crew_kwargs.append("verbose=False")
        else:
            crew_kwargs.append("verbose=True")
            
        if getattr(data, 'memory', False) is True:
            crew_kwargs.append("memory=True")
            
        if getattr(data, 'cache', True) is False:
            crew_kwargs.append("cache=False")
            
        if getattr(data, 'planning', False) is True:
            crew_kwargs.append("planning=True")
            
        if getattr(data, 'share_crew', False) is True:
            crew_kwargs.append("share_crew=True")
            
        max_rpm = getattr(data, 'max_rpm', None)
        if max_rpm is not None:
            crew_kwargs.append(f"max_rpm={max_rpm}")
            
    if agent_llms and crew_node:
        manager_llm = agent_llms.get(f"manager_{crew_node.id}")
        if manager_llm:
            crew_kwargs.append(f"manager_llm='{manager_llm['model']}'")
            
        planning_llm = agent_llms.get(f"planning_{crew_node.id}")
        if planning_llm:
            crew_kwargs.append(f"planning_llm='{planning_llm['model']}'")
            
        fc_llm = agent_llms.get(f"function_calling_{crew_node.id}")
        if fc_llm:
            crew_kwargs.append(f"function_calling_llm='{fc_llm['model']}'")
            
        embedder_conf = getattr(data, 'embedder', None)
        if embedder_conf:
            crew_kwargs.append(f"embedder={embedder_conf}")
            
        output_log = getattr(data, 'output_log_file', None)
        if output_log:
            crew_kwargs.append(f"output_log_file='{output_log}'")
            
        prompt_file = getattr(data, 'prompt_file', None)
        if prompt_file:
            crew_kwargs.append(f"prompt_file='{prompt_file}'")

    crew_kwargs_str = ",\n            ".join(crew_kwargs)

    tools_import = ""
    if needed_tools_imports:
        for slug, func in needed_tools_imports:
            tools_import += f"\nfrom .tools.{slug} import {func}"

    crewai_tools_import = ""
    if needed_crewai_tools:
        crewai_tools_import = f"\nfrom crewai_tools import {', '.join(sorted(list(needed_crewai_tools)))}"

    content = f"""from crewai import Agent, Crew, Process, Task
from crewai.project import CrewBase, agent, crew, task{crewai_tools_import}{tools_import}
from pydantic import Field
import os
from typing import Any

# --- WORKSPACE AWARE FILE TOOLS ---
class WorkspaceFileReadTool(FileReadTool):
    workspace_path: str = Field(..., description="The root path of the workspace")
    
    def _run(self, **kwargs: Any) -> str:
        file_path = kwargs.get('file_path') or self.file_path
        if file_path:
            abs_workspace = os.path.abspath(self.workspace_path)
            if not os.path.isabs(file_path):
                file_path = os.path.join(abs_workspace, file_path)
            kwargs['file_path'] = file_path
        return super()._run(**kwargs)

class WorkspaceFileWriterTool(FileWriterTool):
    workspace_path: str = Field(..., description="The root path of the workspace")
    
    def _run(self, **kwargs: Any) -> str:
        requested_dir = kwargs.get('directory')
        abs_workspace = os.path.abspath(self.workspace_path)
        if not requested_dir or not os.path.isabs(requested_dir):
            if not requested_dir or requested_dir == "./":
                kwargs['directory'] = abs_workspace
            else:
                kwargs['directory'] = os.path.join(abs_workspace, requested_dir.lstrip('./\\\\'))
        return super()._run(**kwargs)

@CrewBase
class {class_name}():
    \"\"\"Orquestração de agentes gerada pelo SimpleCrew\"\"\"
    agents_config = 'config/agents.yaml'
    tasks_config = 'config/tasks.yaml'

    def __init__(self, mcp_tools=None):
        self.mcp_tools = mcp_tools or {{}}

    {agents_methods}
    {tasks_methods}

    @crew
    def crew(self) -> Crew:
        \"\"\"Cria a Crew com os agentes e tarefas definidos\"\"\"
        return Crew(
            {crew_kwargs_str}
        )
"""
    return content


def generate_langgraph_project(graph_data: GraphData, project_name: str, author_name: str = "SimpleCrew", author_email: str = "admin@simplecrew.ai", mcp_servers: List[Dict[str, Any]] = None, project_description: str = "", agent_llms: Dict[str, Dict[str, Any]] = None, providers: List[str] = None, workspace_path: str = None) -> bytes:
    """
    Transforma GraphData em um arquivo ZIP contendo um projeto LangGraph completo.
    """
    folder_name = to_snake_case(project_name)
    if not folder_name:
        folder_name = "my_langgraph_project"

    buffer = io.BytesIO()
    
    with zipfile.ZipFile(buffer, 'a', zipfile.ZIP_DEFLATED, False) as zip_file:
        # 1. .env
        env_lines = []
        needed_keys = []
        providers = providers or ["openai"]
        for p in providers:
            env_key = f"{p.upper()}_API_KEY"
            env_lines.append(f"{env_key}=your_{p}_api_key_here")
            needed_keys.append(env_key)
        
        # Default Tools Keys
        if graph_data.globalTools:
            for tool in graph_data.globalTools:
                if tool.requiresKey and tool.apiKey:
                    env_key = f"{tool.id.upper()}_API_KEY"
                    if tool.id == 'serper': env_key = "SERPER_API_KEY"
                    env_lines.append(f"{env_key}={tool.apiKey}")
                    needed_keys.append(env_key)

        env_content = "\n".join(env_lines) + "\n"
        zip_file.writestr(f"{folder_name}/.env", env_content)
        zip_file.writestr(f"{folder_name}/workspace/.gitkeep", "")

        # 2. pyproject.toml
        pyproject_content = f"""[project]
name = "{folder_name}"
version = "0.1.0"
description = "{project_name} - LangGraph project generated by Simple Crew Builder"
authors = [{{ name = "{author_name}", email = "{author_email}" }}]
requires-python = ">=3.10,<3.14"
dependencies = [
    "langgraph>=0.2.39",
    "langchain>=0.3.0",
    "langchain-openai",
    "langchain-anthropic",
    "langchain-google-genai",
    "langchain-community",
    "jinja2",
    "pydantic>=2.0",
    "crewai-tools[mcp]>=1.10.1"
]

[project.scripts]
{folder_name} = "{folder_name}.main:run"
run_graph = "{folder_name}.main:run"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "langgraph"
"""
        zip_file.writestr(f"{folder_name}/pyproject.toml", pyproject_content)

        # 3. README.md
        readme_content = f"""# {project_name} (LangGraph)
{project_description}

Este projeto foi gerado automaticamente pelo **Simple Crew Builder**. Ele utiliza a estrutura do **LangGraph** para orquestração de agentes.

## 🛠️ Como rodar o projeto

1. **Variaveis de Ambiente:**
   Configure as chaves no arquivo `.env`.

2. **Instalação:**
   ```bash
   uv sync
   ```

3. **Execução:**
   ```bash
   uv run run_graph
   ```

## 📂 Estrutura
- `src/{folder_name}/state.py`: Definição do Estado do Grafo.
- `src/{folder_name}/nodes.py`: Funções integradas dos Agentes e Roteadores.
- `src/{folder_name}/graph.py`: Montagem e compilação do Grafo.
- `src/{folder_name}/main.py`: Ponto de entrada.
"""
        zip_file.writestr(f"{folder_name}/README.md", readme_content)

        package_path = f"{folder_name}/src/{folder_name}"
        zip_file.writestr(f"{package_path}/__init__.py", "")
        zip_file.writestr(f"{folder_name}/src/__init__.py", "")
        
        # Tools
        custom_tools_dict = {t.id: t for t in (graph_data.customTools or [])}
        tools_package_path = f"{package_path}/tools"
        zip_file.writestr(f"{tools_package_path}/__init__.py", "# Custom tools\n")
        
        used_tool_imports = []
        for node in graph_data.nodes:
            if node.type == 'agent':
                ct_ids = getattr(node.data, 'customToolIds', []) or []
                for cid in ct_ids:
                    if cid in custom_tools_dict:
                        t_data = custom_tools_dict[cid]
                        t_slug = to_snake_case(t_data.name) or f"tool_{cid[:8]}"
                        match = re.search(r'def\s+([a-zA-Z0-9_]+)', t_data.code)
                        if match:
                            func_name = match.group(1)
                            used_tool_imports.append((t_slug, func_name))
                            # Write tool file
                            t_content = "from langchain_core.tools import tool\nfrom pydantic import BaseModel, Field\nimport os\nimport json\n\n"
                            if "@tool" not in t_data.code:
                                t_content += f"@tool(\"{func_name}\")\n" + t_data.code
                            else:
                                t_content += t_data.code
                            zip_file.writestr(f"{tools_package_path}/{t_slug}.py", t_content)

        # Utils
        utils_content = """import os
import re
import jinja2
import json

def normalize_command(command: str) -> str:
    if not command: return command
    if os.name == "nt" and command.lower() in ["npx", "npm"]:
        return f"{command}.cmd"
    return command

def interpolate_prompt(text: str, state: dict) -> str:
    if not text or not isinstance(text, str): return text
    result = text
    try:
        for key, value in state.items():
            str_val = None
            if isinstance(value, (str, int, float, bool)) or value is None:
                str_val = str(value) if value is not None else ""
            elif isinstance(value, (list, tuple)) and key == 'messages':
                history_texts = []
                for m in value:
                    v_type = getattr(m, 'type', type(m).__name__).upper()
                    v_name = getattr(m, 'name', v_type)
                    v_content = getattr(m, 'content', str(m))
                    history_texts.append(f"{v_name}: {v_content}")
                str_val = "\\n".join(history_texts)
            if str_val is not None:
                result = re.sub(r'(?<!\\{)\\{' + re.escape(key) + r'\\}(?!\\})', lambda _: str_val, result)
        if '{%' in result or '{{' in result:
            try:
                template = jinja2.Template(result)
                result = template.render(**state)
            except: pass
        return result
    except: return text
"""
        zip_file.writestr(f"{package_path}/utils.py", utils_content)

        # State, Nodes, Graph, Main
        zip_file.writestr(f"{package_path}/state.py", generate_langgraph_state_py(graph_data))
        zip_file.writestr(f"{package_path}/nodes.py", generate_langgraph_nodes_py(graph_data, agent_llms, used_tool_imports))
        zip_file.writestr(f"{package_path}/graph.py", generate_langgraph_graph_py(graph_data))
        zip_file.writestr(f"{package_path}/main.py", generate_langgraph_main_py(folder_name, graph_data, mcp_servers))

    return buffer.getvalue()

def generate_langgraph_state_py(graph_data: GraphData) -> str:
    state_node = next((n for n in graph_data.nodes if n.type == 'state'), None)
    if not state_node: return "from typing import TypedDict, Annotated, List, Any\nfrom langgraph.graph.message import add_messages\n\nclass State(TypedDict):\n    messages: Annotated[List[Any], add_messages]\n"
    
    fields = []
    imports = ["from typing import TypedDict, Annotated, List, Any, Dict", "from langgraph.graph.message import add_messages", "import operator"]
    
    type_map = {"string": "str", "integer": "int", "float": "float", "boolean": "bool", "list": "list", "dict": "dict", "any": "Any"}
    
    # Check for schemas/TypedDicts needed
    schema_nodes = [n for n in graph_data.nodes if n.type == 'schema']
    schemas_code = ""
    for s in schema_nodes:
        s_name = s.data.name or f"Schema_{s.id[:8]}"
        schemas_code += f"\nclass {s_name}(TypedDict):\n"
        for f in s.data.fields:
            ftype = type_map.get(f.type.lower(), "Any")
            schemas_code += f"    {f.key}: {ftype}\n"
            
    for f in state_node.data.fields:
        base_type = type_map.get(f.type.lower(), "Any")
        if f.reducer in ["add", "append"]:
            reducer = "add_messages" if f.key == "messages" else "operator.add"
            fields.append(f"    {f.key}: Annotated[{base_type}, {reducer}]")
        else:
            fields.append(f"    {f.key}: {base_type}")
            
    if "messages" not in [f.key for f in state_node.data.fields]:
        fields.append("    messages: Annotated[List[Any], add_messages]")
        
    fields.append("    task_progress: Annotated[Dict[str, int], lambda a, b: {**(a or {}), **(b or {})}]")

    return "\n".join(imports) + "\n" + schemas_code + "\nclass State(TypedDict):\n" + "\n".join(fields) + "\n"

def generate_langgraph_nodes_py(graph_data: GraphData, agent_llms: Dict[str, Any], tool_imports: List[tuple]) -> str:
    content = "import operator\nfrom typing import Dict, Any, List, Annotated\nfrom langchain_core.messages import SystemMessage, HumanMessage, AIMessage\n"
    content += "from langchain_openai import ChatOpenAI\nfrom langchain_anthropic import ChatAnthropic\nfrom langchain_google_genai import ChatGoogleGenerativeAI\n"
    content += "from langgraph.prebuilt import ToolNode\n"
    content += "from crewai_tools import FileReadTool, FileWriterTool, DirectoryReadTool\n"
    content += "from .state import State\nfrom .utils import interpolate_prompt\n"
    
    for slug, func in tool_imports:
        content += f"from .tools.{slug} import {func}\n"

    content += """
def get_model(provider, model_name):
    if "anthropic" in provider: return ChatAnthropic(model=model_name)
    if "google" in provider: return ChatGoogleGenerativeAI(model=model_name)
    return ChatOpenAI(model=model_name)

def get_agent_tools(mcp_tools_adapter, custom_tools_map, global_tool_ids):
    tools = []
    # 1. Official/Global Tools (FileSystem targeted)
    for g_id in (global_tool_ids or []):
        if g_id == 'file_read': tools.append(FileReadTool())
        elif g_id == 'file_write': tools.append(FileWriterTool())
        elif g_id == 'directory_read': tools.append(DirectoryReadTool())
        
    # 2. MCP Tools
    if mcp_tools_adapter:
        tools.extend(mcp_tools_adapter.tools)
        
    # 3. Custom Tools
    for t in custom_tools_map.values():
        tools.append(t)
        
    return tools
"""

    for node in graph_data.nodes:
        if node.type == 'agent':
            llm_info = agent_llms.get(node.id, {"model": "gpt-4o", "provider": "openai"})
            name = to_snake_case(node.data.name or "agent")
            
            ct_ids = getattr(node.data, 'customToolIds', []) or []
            my_ct_map = {}
            for cid in ct_ids:
                ct = next((t for t in graph_data.customTools if t.id == cid), None)
                if ct:
                    slug = to_snake_case(ct.name)
                    for s, f in tool_imports:
                        if s == slug: my_ct_map[cid] = f
            
            global_tool_ids = getattr(node.data, 'globalToolIds', []) or []
            # Extract just IDs if they are dicts
            clean_global_ids = [g if isinstance(g, str) else g.get('id') for g in global_tool_ids if g]

            content += f"""
def {name}_node(state: State, config: Dict[str, Any] = None):
    # Injected runtime MCP tools
    mcp_tools_adapter = (config or {{}}).get("configurable", {{}}).get("mcp_tools_adapter")
    
    # Custom tools imported in this module
    custom_tools_map = {{k: globals()[v] for k, v in {my_ct_map}.items() if v in globals()}}
    
    tools = get_agent_tools(mcp_tools_adapter, custom_tools_map, {clean_global_ids})
    model = get_model("{llm_info['provider']}", "{llm_info['model']}")
    if tools:
        model = model.bind_tools(tools)
    
    role = interpolate_prompt(\"\"\"{node.data.role}\"\"\", state)
    goal = interpolate_prompt(\"\"\"{node.data.goal}\"\"\", state)
    backstory = interpolate_prompt(\"\"\"{node.data.backstory}\"\"\", state)
    
    sys_content = f"Role: {{role}}\\nGoal: {{goal}}\\nBackstory: {{backstory}}"
    
    task_ids = {getattr(node.data, 'taskOrder', [])}
    progress = state.get("task_progress", {{}}).get("{node.id}", 0)
    if task_ids and progress < len(task_ids):
        sys_content += f"\\n\\nActive Task: {{task_ids[progress]}}"
    
    messages = [SystemMessage(content=sys_content)] + state['messages']
    response = model.invoke(messages)
    
    return {{"messages": [response], "task_progress": {{"{node.id}": progress + 1}}}}
"""
        elif node.type == 'router':
            name = to_snake_case(node.data.name or "router")
            content += f"""
def {name}_node(state: State):
    return {{}}
"""
    return content

def generate_langgraph_graph_py(graph_data: GraphData) -> str:
    content = "from langgraph.graph import StateGraph, END\nfrom langgraph.prebuilt import ToolNode, tools_condition\nfrom .state import State\nfrom .nodes import *\n\nbuilder = StateGraph(State)\n"
    
    nodes_map = {n.id: n for n in graph_data.nodes}
    functional_nodes = [n for n in graph_data.nodes if n.type in ['agent', 'router', 'crew']]
    
    # Tool Resolution for nodes
    for n in functional_nodes:
        name = to_snake_case(n.data.name or n.type)
        content += f"builder.add_node(\"{n.id}\", {name}_node)\n"
        
        has_tools = (getattr(n.data, 'customToolIds', []) or getattr(n.data, 'mcpServerIds', []) or getattr(n.data, 'globalToolIds', []))
        if has_tools:
            # We need to pass the tools to ToolNode. 
            # For exported code, we'll try to resolve them from the nodes module or imports.
            # Here we'll use a placeholder ToolNode that will be properly configured at runtime via config
            # or we can try to pass the static ones if known.
            content += f"builder.add_node(\"{n.id}_tools\", ToolNode([])) # Tools dynamically resolved via nodes\n"

    for edge in graph_data.edges:
        source_node = nodes_map.get(edge.source)
        if not source_node or source_node.type == 'router': continue
            
        if source_node.type == 'agent':
            has_tools = (getattr(source_node.data, 'customToolIds', []) or getattr(source_node.data, 'mcpServerIds', []) or getattr(source_node.data, 'globalToolIds', []))
            if has_tools:
                content += f"builder.add_conditional_edges(\"{edge.source}\", tools_condition, {{\n"
                content += f"    \"tools\": \"{edge.source}_tools\",\n"
                content += f"    \"__end__\": \"{edge.target}\"\n"
                content += f"}})\n"
                content += f"builder.add_edge(\"{edge.source}_tools\", \"{edge.source}\")\n"
                continue

        content += f"builder.add_edge(\"{edge.source}\", \"{edge.target}\")\n"
        
    for n in functional_nodes:
        if n.type == 'router':
            name = to_snake_case(n.data.name or "router")
            conditions = getattr(n.data, 'conditions', []) or []
            default_route = getattr(n.data, 'defaultRoute', 'END')
            
            path_map = {}
            for edge in graph_data.edges:
                if edge.source == n.id and edge.sourceHandle:
                    path_map[edge.sourceHandle] = edge.target
            
            content += f"\ndef {name}_condition(state: State):\n"
            
            if not conditions:
                content += f"    return \"{default_route}\"\n\n"
            else:
                op_map = {
                    "==": "==", "!=": "!=", ">": ">", "<": "<", 
                    ">=": ">=", "<=": "<=", "contains": "in", "not_contains": "not in"
                }
                
                for i, cond in enumerate(conditions):
                    op = op_map.get(cond.operator, "==")
                    val = json.dumps(cond.value)
                    
                    if cond.operator in ["contains", "not_contains"]:
                        expr = f"{val} {op} state.get('{cond.field}', '')"
                    else:
                        expr = f"state.get('{cond.field}') {op} {val}"
                        
                    if_stmt = "if" if i == 0 else "elif"
                    target = path_map.get(cond.id, default_route)
                    content += f"    {if_stmt} {expr}:\n        return \"{target}\"\n"
                
                content += f"    return \"{default_route}\"\n\n"
            
            # Collect all possible targets for conditional edges mapping
            all_targets = set(path_map.values())
            all_targets.add(default_route)
            edge_map = {t: t for t in all_targets}
            
            content += f"builder.add_conditional_edges(\"{n.id}\", {name}_condition, {json.dumps(edge_map)})\n"

    entry = functional_nodes[0].id if functional_nodes else "END"
    content += f"builder.set_entry_point(\"{entry}\")\n"
    content += "graph = builder.compile()\n"
    return content

def generate_langgraph_main_py(folder_name: str, graph_data: GraphData, mcp_servers: List[Dict]) -> str:
    mcp_setup_code = ""
    mcp_import = ""
    config_entry = ""
    
    if mcp_servers:
        mcp_import = "\nfrom contextlib import ExitStack\nfrom crewai_tools import MCPServerAdapter\nfrom mcp import StdioServerParameters\nfrom .utils import normalize_command"
        mcp_setup_code = "\n    # Setup MCP Servers\n    with ExitStack() as stack:\n"
        mcp_setup_code += "        adapters = []\n"
        for s in mcp_servers:
            mcp_setup_code += f"        # {s['name']}\n"
            mcp_setup_code += f"        params_{to_snake_case(s['name'])} = StdioServerParameters(\n"
            mcp_setup_code += f"            command=normalize_command({json.dumps(s['command'])}) if {json.dumps(s['command'])} else None,\n"
            mcp_setup_code += f"            args={json.dumps(s['args']) or '[]'},\n"
            mcp_setup_code += f"            env={json.dumps(s['env_vars']) or 'None'}\n"
            mcp_setup_code += f"        )\n"
            mcp_setup_code += f"        adapters.append(stack.enter_context(MCPServerAdapter(params_{to_snake_case(s['name'])})))\n"
        
        mcp_setup_code += "\n        # Combine adapters for the graph\n"
        config_entry = ", config={\"configurable\": {\"mcp_tools_adapter\": adapters[0] if adapters else None}}"

    return f"""from .graph import graph{mcp_import}
import json

def run():
    print("--- Running LangGraph Workflow ---")
    
    # Initial state (can be customized)
    initial_state = {{"messages": [], "task_progress": {{}}}}
    
    # Execution configuration
    thread_id = "1"
    config = {{"configurable": {{"thread_id": thread_id}}}}{config_entry}

    try:
{mcp_setup_code if mcp_servers else ""}
        for output in graph.stream(initial_state, config=config, recursion_limit=50):
            for key, value in output.items():
                print(f"\\n[Node: {{key}}]")
                if 'messages' in value:
                    last_msg = value['messages'][-1]
                    print(f"Content: {{getattr(last_msg, 'content', str(last_msg))[:200]}}...")
    except Exception as e:
        print(f"Error executing graph: {{e}}")

if __name__ == "__main__":
    run()
"""
